### ISSUE TITLE
Invariant Violation: Picker has been removed from React Native. It can now be installed and imported from '@react-native-picker/picker' instead of 'react-native'.

### ISSUE THREAD

**Issue by vuletuanbt** [lawnstarter/react-native-picker-select#469]
**Describe the bug**<br />

**To Reproduce**<br />

1.  Install package 
2. Install @react-native-picker/picker
3.  See an error

**Expected behavior**<br />
Can open screen

**Screenshots**<br />
![image](https://user-images.githubusercontent.com/13297069/142379931-736b4a6b-1539-458f-8291-994436ecade6.png)

**Additional details**<br />
-   Device: Samsung M21
-   OS: Android & IOs
-   react-native-picker-select version: 8.0.4
-   react-native version: 0.66.3
-   expo sdk version:  N/A

**Reproduction and/or code sample**<br />

**Comment by vuletuanbt** [comment]
My issue was resolved, it works with https://github.com/lawnstarter/react-native-picker-select/issues/404#issuecomment-972880629

**Comment by ParthShrivastav** [comment]
Issue is still persisting even after trying the above solution
