### ISSUE TITLE
IOS Carousel triggers crash after several up/down scrolls

### ISSUE THREAD

**Issue by melnykandrii** [lawnstarter/react-native-picker-select#707]
**Describe the bug**<br />
The react-native-picker-select after scrolling IOS carousel up and down several times crashes at some point,  this issue continuously reproducible with different devices and started after update to `react-native@0.79.5` with the new architecture.

**To Reproduce**<br />

1.  Open the IOS carousel 
2.  Scroll several times down and up, if not close the carousel and open again, repeat up/down movement several times.
3.  Crashes the app.

**Expected behavior**<br />
The IOS carousel works as expected and the user can select the option, no crash happening.

**Screenshots**<br />
![Image](https://github.com/user-attachments/assets/6125b988-f459-4023-9f72-75442fecc946)

**Additional details**<br />
-   Device: iPhoneXSMax
-   OS: iOS18.6.2
-   react-native-picker-select version:  9.3.1
-   react-native version: 0.79.5
-   expo sdk version: 53.0.20

**Reproduction and/or code sample**<br />
[Provide a link to a reproduction of this issue on https://snack.expo.io **or an explanation why you can not**. Not including a snack link will result in a significant delay in our ability to address this issue.](https://snack.expo.dev/@andriimelnyk/picker-select-ios-carousel-crash-on-interaction)

Crash report attached:

[com.smartdrive.smartdrive_issue_a867e01f86f0e3927cdea2b18a75266d_crash_session_00945f78be2b4c10baed0705fd332835_DNE_0_v2_stacktrace.txt](https://github.com/user-attachments/files/22433863/com.smartdrive.smartdrive_issue_a867e01f86f0e3927cdea2b18a75266d_crash_session_00945f78be2b4c10baed0705fd332835_DNE_0_v2_stacktrace.txt)

**Comment by irajangarg** [comment]
I am also getting the same issue. Any updates here?

**Comment by noamyagil** [comment]
+1

**Comment by paulinhapenedo** [comment]
This crash is caused by an upstream bug in **@react-native-picker/picker**, fixed in **v2.11.4** — "Set delegate properly in new architecture to resolve question marks display issue" (iOS New Architecture delegate handling). Please update your `@react-native-picker/picker` dependency to `^2.11.3` or higher. We have also bumped our minimum peer dependency to `^2.11.3`.

**Comment by dhairyasenjaliya** [comment]
can still did the crash even after  @react-native-picker/picker dependency to ^2.11.3 any one faces same

**Comment by ngandhy** [comment]
@paulinhapenedo - it's definitely upstream but seems to be still occuring. [vlad-lazovsky](https://github.com/vlad-lazovsky) patch here: https://github.com/react-native-picker/picker/issues/627#issuecomment-3481692905 seems to fix it
